// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final_vjwill77.Models;

#nullable disable

namespace final_vjwill77.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210023106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("final_vjwill77.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("final_vjwill77.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShirtSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("final_vjwill77.Models.ParticipantCourse", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantCourseCourseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantCourseParticipantID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseID", "ParticipantID");

                    b.HasIndex("ParticipantID");

                    b.HasIndex("ParticipantCourseCourseID", "ParticipantCourseParticipantID");

                    b.ToTable("ParticipantCourses");
                });

            modelBuilder.Entity("final_vjwill77.Models.ParticipantCourse", b =>
                {
                    b.HasOne("final_vjwill77.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("final_vjwill77.Models.Participant", "Participant")
                        .WithMany("ParticipantCourses")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("final_vjwill77.Models.ParticipantCourse", null)
                        .WithMany("ParticipantCourses")
                        .HasForeignKey("ParticipantCourseCourseID", "ParticipantCourseParticipantID");

                    b.Navigation("Course");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("final_vjwill77.Models.Participant", b =>
                {
                    b.Navigation("ParticipantCourses");
                });

            modelBuilder.Entity("final_vjwill77.Models.ParticipantCourse", b =>
                {
                    b.Navigation("ParticipantCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
